#!/bin/bash
# make-formula.sh — render (or verify) the Homebrew formula for a released tag.
#
# The formula is GENERATED, not hand-edited: its version, url and sha256 have to
# agree with VERSION and with a tag that actually exists on GitHub. Hand-editing
# three coupled fields is how taps end up serving the previous release forever.
#
#   scripts/make-formula.sh            render packaging/homebrew for $(cat VERSION)
#   scripts/make-formula.sh 0.3.0      render for an explicit version
#   scripts/make-formula.sh --check    verify the committed formula matches VERSION
#                                      (offline; make check runs this)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$HERE/packaging/homebrew/cmux-sentinel.rb"
REPO="oliver-kriska/cmux-sentinel"

check=0
case "${1:-}" in
  --check) check=1; shift ;;
  -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
esac
ver="${1:-$(cat "$HERE/VERSION")}"

# --check must stay OFFLINE: it runs in CI and in the pre-commit hook, where a
# network failure would block a commit that has nothing to do with packaging.
if [ "$check" = 1 ]; then
  # The formula is a RELEASE artifact: it cannot exist before the tag it hashes.
  # Absent is therefore "not released yet", not a failure — otherwise every commit
  # between a version bump and its tag would be blocked. A formula that EXISTS and
  # disagrees with VERSION is the real bug, and is caught below.
  if [ ! -f "$OUT" ]; then
    echo "formula: none yet (v$ver not released) — after tagging: scripts/make-formula.sh"
    exit 0
  fi
  fver="$(sed -n 's/.*archive\/refs\/tags\/v\([0-9.]*\)\.tar\.gz.*/\1/p' "$OUT" | head -1)"
  if [ "$fver" != "$ver" ]; then
    echo "formula is for v$fver but VERSION says $ver" >&2
    echo "  after tagging v$ver:  scripts/make-formula.sh   (then commit the formula)" >&2
    exit 1
  fi
  grep -q 'sha256 "[0-9a-f]\{64\}"' "$OUT" || { echo "formula has no real sha256" >&2; exit 1; }
  echo "formula: v$fver ✓"
  exit 0
fi

url="https://github.com/$REPO/archive/refs/tags/v$ver.tar.gz"
echo "Hashing $url"
# A tag that doesn't exist yet returns a 404 page, and shasum would happily hash
# it — so fail on the HTTP status, not on the download succeeding.
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
code="$(curl -sSL -w '%{http_code}' -o "$tmp" "$url")"
[ "$code" = 200 ] || { echo "GitHub returned $code — is v$ver tagged and pushed?" >&2; exit 1; }
sha="$(shasum -a 256 "$tmp" | awk '{print $1}')"

cat > "$OUT" <<RB
# Generated by scripts/make-formula.sh — do not hand-edit; regenerate for a new tag.
class CmuxSentinel < Formula
  desc "Opinionated cmux sidebar with agent-state rows and AI usage meters"
  homepage "https://github.com/$REPO"
  url "$url"
  sha256 "$sha"
  license "MIT"

  depends_on "jq"
  depends_on :macos

  def install
    # The WHOLE tree, not just bin/: install.sh also deploys sidebars/, hooks/ and
    # the launchd templates, and it locates them relative to itself.
    libexec.install Dir["*"]
    # Deliberately not bin.install_symlink: through a symlink \$0 stays in the
    # prefix's bin/, where none of the cmux-*.sh helpers live, and the dispatcher
    # would fail to resolve them. write_exec_script execs the real libexec path.
    bin.write_exec_script libexec/"bin/cmux-sentinel"
  end

  # Homebrew prints caveats only on the FIRST install, never on upgrade — and the
  # message that has to survive an upgrade is exactly this one, because brew
  # updates the Cellar copy while launchd keeps running the scripts in ~/bin.
  def post_install
    ohai "Run 'cmux-sentinel deploy' to install this version into ~/bin and ~/.config"
  end

  def caveats
    <<~EOS
      Homebrew installed the files; two commands finish the job:

        cmux-sentinel deploy    # sidebar, pollers, launchd agents, hooks -> \$HOME
        cmux-sentinel doctor    # confirm the pipeline is wired

      Run 'deploy' after every upgrade too: the launchd agents run the copies in
      ~/bin, so a new formula alone changes nothing that is actually executing.
    EOS
  end

  test do
    assert_match "cmux-sentinel deploy", shell_output("#{bin}/cmux-sentinel help")
    # An unknown command must fail loudly (exit 2), never silently no-op.
    shell_output("#{bin}/cmux-sentinel definitely-not-a-command 2>&1", 2)
  end
end
RB
echo "wrote $OUT  (v$ver, sha256 ${sha:0:12}…)"
